### ISSUE TITLE
Update nuget package 

### ISSUE THREAD

**Issue by mexzar** [jsmarble/YNAB.Rest#9]
The latest on nuget is out of date with the source code (specifically, being able to specify a start date for get transactions).

Could you update?

And thanks for the simple/easy to use library!

**Comment by websmartcentral** [comment]
Agreed it is a good library - we are fortunate to have it

I embed the code direct - so didn't bother with the nuget (which is probably what you ended up doing as well?)

**Comment by mexzar** [comment]
Yes, that's right (although I would have loved to just use nuget to manage this dependency). Not a big deal though.

**Comment by jsmarble** [comment]
Sorry I have been slow to get back to this. Yes, I will get the nuget package updated with the latest source. I need to work on automating that. I will update here and close the issue when it's updated.

**Comment by jsmarble** [comment]
This project also [exists on GitLab](https://gitlab.com/jsmarble/YNAB-Rest) because I switched to using their pipelines and there were some code changes over there in recent nuget versions that were not in the code on GitHub. I reconciled the two projects, built a nuget package with version `1.1.0` and published that to the nuget gallery. It should be available soon. The GitHub and GitLab source code is currently the same. Cheers!
